{% set name = "qcxms" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v.{{ version }}.tar.gz
    sha256: 738549d12e4a20f69df8069dacf3aecdd85eac633896faa23cb72f1ffb8a2bfe
    patches:
      - meson.patch  # [osx]
  - url: https://github.com/grimme-lab/rmsd-tool/archive/refs/tags/v0.1.1.tar.gz
    sha256: b3105e1b23695c2a1393469dda944d5dba44a75a407a1266f87ea72289d66c64
    folder: subprojects/rmsd-tool
    patches:
      - rmsd-tool.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('fortran') }}
    - meson
    - ninja
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - liblapack
    - mctc-lib >=0.3.0
    - tblite >=0.2.0
    - toml-f

test:
  commands:
    - test -f $PREFIX/bin/{{ name }}

about:
  home: https://github.com/qcxms/qcxms
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
    - subprojects/rmsd-tool/COPYING
    - subprojects/rmsd-tool/COPYING.LESSER
  summary: Quantum mechanic mass spectrometry calculation program
  doc_url: https://xtb-docs.readthedocs.io/en/latest/qcxms_doc/qcxms.html

extra:
  recipe-maintainers:
    - awvwgk
    - JayTheDog
